In [1]:
import folium
import json
import pandas as pd
import numpy as np
import geopandas as gpd
import fiona
import os
import seaborn as sns
import matplotlib.pyplot as plt
from shapely.geometry import Polygon, LineString, Point
from tqdm import tqdm

In [5]:
# 데이터 불러오기 

data1 = pd.read_csv("data/compas/1.오산시_주정차단속(2018~2020).csv")
data2 = gpd.read_file("data/compas/4.오산시_연령별_거주인구격자(총인구).geojson")

data3 = gpd.read_file("data/compas/3.오산시_차량등록현황_격자.geojson")
data5 = gpd.read_file("data/compas/5.오산시_연령별_거주인구격자(유소년).geojson")
data6 = gpd.read_file("data/compas/6.오산시_연령별_거주인구격자(생산가능인구).geojson")
data7 = gpd.read_file("data/compas/7.오산시_연령별_거주인구격자(고령).geojson")
data9 = pd.read_csv("data/compas/9.오산시_어린이보호구역.csv")
data10 = pd.read_csv("data/compas/10.오산시_학교위치정보.csv")

data11 = gpd.read_file("data/compas/11.오산시_초등학교_통학구.geojson")
data12 = gpd.read_file("data/compas/12.오산시_중학교_학군.geojson")
data13 = pd.read_csv("data/compas/13.오산시_어린이집_유치원현황.csv")
data15 = pd.read_csv("data/compas/15.오산시_무인교통단속카메라.csv")
data16 = pd.read_csv("data/compas/16.오산시_도로안전표지표준데이터.csv")
data17 = gpd.read_file("data/compas/17.오산시_횡단보도.geojson")

"""
data18 = pd.read_csv("18.오산시_과속방지턱표준데이터.csv")
data19 = gpd.read_file("19.오산시_신호등.geojson")
data20 = pd.read_csv("20.오산시_CCTV설치현황.csv")
data21 = gpd.read_file("21.오산시_인도.geojson")
data22 = pd.read_csv("22.오산시_버스정류장.csv")
data23 = gpd.read_file("23.오산시_상세도로망_LV6.geojson")
data24 = pd.read_csv("24.평일_전일,시간대별_오산시_추정교통량_Level6.csv")
data25  = pd.read_csv("25.평일_전일_오산시_혼잡빈도강도_Level6.csv")
data26 = pd.read_csv("26.평일_전일_오산시_혼잡시간강도_Level6.csv")
data27 = gpd.read_file("27.오산시_도로명주소_건물.geojson")
data28 = gpd.read_file("28.오산시_건물연면적_격자.geojson")
data29 = pd.read_csv('29.오산시_체육시설현황.csv')
data30 = pd.read_csv("30.오산시_학원_및_교습소_현황.csv")
data33 = gpd.read_file('33.오산시_법정경계(읍면동).geojson')
data34 = gpd.read_file("34.오산시_지적도.geojson")
"""

'\ndata18 = pd.read_csv("18.오산시_과속방지턱표준데이터.csv")\ndata19 = gpd.read_file("19.오산시_신호등.geojson")\ndata20 = pd.read_csv("20.오산시_CCTV설치현황.csv")\ndata21 = gpd.read_file("21.오산시_인도.geojson")\ndata22 = pd.read_csv("22.오산시_버스정류장.csv")\ndata23 = gpd.read_file("23.오산시_상세도로망_LV6.geojson")\ndata24 = pd.read_csv("24.평일_전일,시간대별_오산시_추정교통량_Level6.csv")\ndata25  = pd.read_csv("25.평일_전일_오산시_혼잡빈도강도_Level6.csv")\ndata26 = pd.read_csv("26.평일_전일_오산시_혼잡시간강도_Level6.csv")\ndata27 = gpd.read_file("27.오산시_도로명주소_건물.geojson")\ndata28 = gpd.read_file("28.오산시_건물연면적_격자.geojson")\ndata29 = pd.read_csv(\'29.오산시_체육시설현황.csv\')\ndata30 = pd.read_csv("30.오산시_학원_및_교습소_현황.csv")\ndata33 = gpd.read_file(\'33.오산시_법정경계(읍면동).geojson\')\ndata34 = gpd.read_file("34.오산시_지적도.geojson")\n'

In [6]:
data2

           gid  val                                           geometry
0     다사551085  NaN  MULTIPOLYGON (((126.99422 37.17418, 126.99421 ...
1     다사551086  NaN  MULTIPOLYGON (((126.99421 37.17508, 126.99420 ...
2     다사551087  NaN  MULTIPOLYGON (((126.99420 37.17599, 126.99420 ...
3     다사551088  NaN  MULTIPOLYGON (((126.99420 37.17689, 126.99419 ...
4     다사552085  NaN  MULTIPOLYGON (((126.99534 37.17419, 126.99534 ...
...        ...  ...                                                ...
4505  다사646052  NaN  MULTIPOLYGON (((127.10138 37.14484, 127.10138 ...
4506  다사646053  NaN  MULTIPOLYGON (((127.10138 37.14575, 127.10137 ...
4507  다사647050  NaN  MULTIPOLYGON (((127.10252 37.14305, 127.10251 ...
4508  다사647051  NaN  MULTIPOLYGON (((127.10251 37.14395, 127.10251 ...
4509  다사647052  NaN  MULTIPOLYGON (((127.10251 37.14485, 127.10250 ...

[4510 rows x 3 columns]

In [7]:
# 격자 데이터
data_gid = data2[['gid', 'geometry']]

In [9]:
data1 = pd.read_csv("data/compas/1.오산시_주정차단속(2018~2020).csv")

In [10]:
data1

,단속일자,단속위치,행정구역,스쿨존여부,단속위치_경도,단속위치_위도,단속종류
0,20181101,금암동 여계산로 부근,경기도 오산시 세교동,N,127.043462,37.170237,이동형CCTV단속
1,20181101,세교동 세마역로19번길,경기도 오산시 세교동,N,127.044770,37.181695,이동형CCTV단속
2,20181101,세교동 수목원로 부근,경기도 오산시 양산동,N,127.042200,37.186357,이동형CCTV단속
3,20181101,오산동 오산로272번길 부,경기도 오산시 원동,N,127.071732,37.150557,이동형CCTV단속
4,20181101,오산동 성호대로93번길,경기도 오산시 부산동,N,127.071757,37.150457,이동형CCTV단속
...,...,...,...,...,...,...,...
61696,20201111,GS25궐동대호점 맞은편,경기도 오산시 청학동,N,127.053064,37.158140,고정형CCTV단속
61697,20201111,물향기지하도,경기도 오산시 원동,N,127.066157,37.171143,고정형CCTV단속
61698,20201111,운암2단지 근린공원삼거,경기도 오산시 청호동,N,127.077283,37.158126,고정형CCTV단속
61699,20201111,궐동 양평해장국 사거리,경기도 오산시 궐동,N,127.056665,37.155827,고정형CCTV단속
61700,20201111,어울림(북개천) 사거리,경기도 오산시 부산동,N,127.068644,37.143810,고정형CCTV단속

In [11]:
data1['PSC_cnt']=1
data1['단속위치_경도'] = data1['단속위치_경도'].astype(float)
data1['단속위치_위도'] = data1['단속위치_위도'].astype(float)
data1['point'] = data1.apply(lambda row : Point([row['단속위치_경도'], row['단속위치_위도']]), axis=1)
data1 = gpd.GeoDataFrame(data1, geometry='point')

In [12]:
data1

,단속일자,단속위치,행정구역,스쿨존여부,단속위치_경도,단속위치_위도,단속종류,PSC_cnt,point
0,20181101,금암동 여계산로 부근,경기도 오산시 세교동,N,127.043462,37.170237,이동형CCTV단속,1,POINT (127.04346 37.17024)
1,20181101,세교동 세마역로19번길,경기도 오산시 세교동,N,127.044770,37.181695,이동형CCTV단속,1,POINT (127.04477 37.18169)
2,20181101,세교동 수목원로 부근,경기도 오산시 양산동,N,127.042200,37.186357,이동형CCTV단속,1,POINT (127.04220 37.18636)
3,20181101,오산동 오산로272번길 부,경기도 오산시 원동,N,127.071732,37.150557,이동형CCTV단속,1,POINT (127.07173 37.15056)
4,20181101,오산동 성호대로93번길,경기도 오산시 부산동,N,127.071757,37.150457,이동형CCTV단속,1,POINT (127.07176 37.15046)
...,...,...,...,...,...,...,...,...,...
61696,20201111,GS25궐동대호점 맞은편,경기도 오산시 청학동,N,127.053064,37.158140,고정형CCTV단속,1,POINT (127.05306 37.15814)
61697,20201111,물향기지하도,경기도 오산시 원동,N,127.066157,37.171143,고정형CCTV단속,1,POINT (127.06616 37.17114)
61698,20201111,운암2단지 근린공원삼거,경기도 오산시 청호동,N,127.077283,37.158126,고정형CCTV단속,1,POINT (127.07728 37.15813)
61699,20201111,궐동 양평해장국 사거리,경기도 오산시 궐동,N,127.056665,37.155827,고정형CCTV단속,1,POINT (127.05666 37.15583)
61700,20201111,어울림(북개천) 사거리,경기도 오산시 부산동,N,127.068644,37.143810,고정형CCTV단속,1,POINT (127.06864 37.14381)

In [13]:
PSC_list = []
for i in tqdm(range(data_gid.shape[0])):
    gid = data_gid['geometry'].iloc[i]
    cnt = data1['point'].within(gid).sum()
    PSC_list.append(cnt)

100%|██| 4510/4510 [25:10<00:00,  2.99it/s]

In [14]:
PSC_cnt = list(PSC_list)
result1 = pd.DataFrame()
result1['gid'] = data_gid['gid']
result1['PSC_cnt'] = PSC_cnt
data1 = result1

In [15]:
result1

           gid  PSC_cnt
0     다사551085        0
1     다사551086        0
2     다사551087        0
3     다사551088        0
4     다사552085        0
...        ...      ...
4505  다사646052        0
4506  다사646053        0
4507  다사647050        0
4508  다사647051        0
4509  다사647052        0

[4510 rows x 2 columns]

In [16]:
result1.PSC_cnt.unique()

array([   0,    4,   42,  163,  203,   10,    1,   57,   21,   14,    2,
         56,   71,    3,   11,    8,   26,   48,   19,   18,    5,   53,
          9,    6,   33,   96,   58,   37,   45,   46,   61,   31,  273,
        750,  604,   15,   24,   27,   23,   25,   44,  498,  308, 2094,
         22,   32,  274,  121,    7,  341,  261, 1574,  217,  380,  313,
        322,   17, 2354,   64, 4286,   16,   28, 2167,   13,  878,   34,
         77,   35,  168,   52,  110,  419,  775,   47,   38,  858,   49,
        760,  745,   36,  279, 1418,  116,  450,   29,   12,   72,  103,
         86,  329,   30,  250,  241,  671,  463,   70,  193,  123,  104,
        126,  177,   73,  516,   97, 1853,   20,   41,  208, 1158,  510,
         40,  102,   85,  109,  120, 1770,  145,   54,  307,  334,   39,
        243,  142,   94,  221,  494,  436,   93,  383,   50,  425,   69,
        117, 1172,  797,   43,  340,   60,  267,  766,  841,  186, 1556,
       1321,  171,  125,  174,  114, 1353,   51,  678,   68,  133,  392,
       1071,  201,  219,  175,  373,  295,  465,   59,   66,   65,  462],
      dtype=int64)

In [18]:
data10 = pd.read_csv("data/compas/10.오산시_학교위치정보.csv")

In [19]:
data10 = data10[data10['학교구분']=='초등학교']
data10.head()

    학교구분     학교명     학교위치_경도    학교위치_위도
0   초등학교  원동초등학교  127.069699  37.135168
1   초등학교  운산초등학교  127.077414  37.152500
2   초등학교  화성초등학교  127.068858  37.164615
12  초등학교  가수초등학교  127.047749  37.147919
13  초등학교  다온초등학교  127.090752  37.151698

In [20]:
data10['school_cnt'] = 1
data10['학교위치_경도'] = data10['학교위치_경도'].astype(float)
data10['학교위치_위도'] = data10['학교위치_위도'].astype(float)
data10['point'] = data10.apply(lambda row : Point([row['학교위치_경도'], row['학교위치_위도']]), axis=1)

In [21]:
data10

,학교구분,학교명,학교위치_경도,학교위치_위도,school_cnt,point
0,초등학교,원동초등학교,127.069699,37.135168,1,POINT (127.0696986 37.1351683)
1,초등학교,운산초등학교,127.077414,37.152500,1,POINT (127.0774136 37.15249986)
2,초등학교,화성초등학교,127.068858,37.164615,1,POINT (127.0688576 37.16461498)
12,초등학교,가수초등학교,127.047749,37.147919,1,POINT (127.0477491 37.14791946)
13,초등학교,다온초등학교,127.090752,37.151698,1,POINT (127.090752 37.1516978)
14,초등학교,매홀초등학교,127.063587,37.162365,1,POINT (127.0635868 37.16236518)
15,초등학교,문시초등학교,127.045862,37.174141,1,POINT (127.0458616 37.17414057)
16,초등학교,성산초등학교,127.066424,37.149695,1,POINT (127.0664245 37.14969499)
17,초등학교,세미초등학교,127.064666,37.173997,1,POINT (127.0646658 37.1739971)
18,초등학교,양산초등학교,127.032111,37.196887,1,POINT (127.0321106 37.19688704)
19,초등학교,오산고현초등학교,127.085531,37.133365,1,POINT (127.0855314 37.13336523)
20,초등학교,오산원당초등학교,127.090864,37.141948,1,POINT (127.0908645 37.14194839)
21,초등학교,오산초등학교,127.049953,37.144756,1,POINT (127.0499533 37.14475593)
22,초등학교,운암초등학교,127.076144,37.143643,1,POINT (127.0761442 37.14364336)
23,초등학교,운천초등학교,127.079173,37.156112,1,POINT (127.0791732 37.15611193)
24,초등학교,광성초등학교,127.040034,37.183802,1,POINT (127.0400336 37.18380171)
33,초등학교,금암초등학교,127.044006,37.178385,1,POINT (127.044006 37.17838514)
34,초등학교,대호초등학교,127.057696,37.158998,1,POINT (127.0576963 37.15899814)
35,초등학교,매홀초등학교삼미분교장,127.063454,37.162672,1,POINT (127.063454 37.162672)
36,초등학교,성호초등학교,127.070972,37.150035,1,POINT (127.0709724 37.15003486)
37,초등학교,수청초등학교,127.055667,37.170668,1,POINT (127.0556667 37.17066759)
38,초등학교,오산대원초등학교,127.071056,37.130446,1,POINT (127.0710562 37.13044603)
39,초등학교,오산원일초등학교,127.071199,37.139366,1,POINT (127.0711992 37.13936633)
40,초등학교,필봉초등학교,127.052553,37.178499,1,POINT (127.0525529 37.178499)

In [22]:
gid_list = []
for i in tqdm(range(data10.shape[0])):
    point = data10['point'].iloc[i]
    g = data_gid['gid'].loc[data_gid['geometry'].contains(point)]
    gid_list.append(g.iloc[0])
data10['gid'] = gid_list

100%|██████| 24/24 [00:00<00:00, 25.59it/s]

In [23]:
result10 = data10.drop(['학교구분', '학교명', '학교위치_경도', '학교위치_위도'],axis=1)
result10 = result10.groupby(['gid']).sum()
result10.reset_index(inplace=True)
data10 = result10

In [24]:
result10

         gid  school_cnt
0   다사584110           1
1   다사591095           1
2   다사595089           1
3   다사596084           1
4   다사598055           1
5   다사600052           1
6   다사602089           1
7   다사605080           1
8   다사607067           1
9   다사612071           2
10  다사613084           1
11  다사614057           1
12  다사617041           1
13  다사617074           1
14  다사618036           1
15  다사619046           1
16  다사619057           1
17  다사623050           1
18  다사624060           1
19  다사626064           1
20  다사631039           1
21  다사636048           1
22  다사636059           1