In [2]:
import geopandas as gpd
출근시간자전거경로 = gpd.read_file('data/자전거 이용 데이터/출근시간대 자전거 이동경로 분포도(2019.10).geojson')
출근시간자전거경로

,OBJECTID,id,Shape_Leng,Shape_Area,LENGTH,COUNT,geometry
0,1.0,0,1199.542584,103843.836728,0.000000,0,"MULTIPOLYGON (((127.05188 37.42734, 127.05301 ..."
1,2.0,1,1199.543181,103843.940068,0.000000,0,"MULTIPOLYGON (((127.04849 37.42890, 127.04962 ..."
2,3.0,2,1199.542348,103843.795889,0.000000,0,"MULTIPOLYGON (((127.05527 37.42890, 127.05640 ..."
3,4.0,3,1199.541515,103843.651618,0.000000,0,"MULTIPOLYGON (((127.06205 37.42890, 127.06318 ..."
4,5.0,4,1199.543556,103844.005026,0.000000,0,"MULTIPOLYGON (((127.04510 37.43046, 127.04623 ..."
...,...,...,...,...,...,...,...
6135,6136.0,6135,1199.543657,103844.022511,419.969699,5,"MULTIPOLYGON (((127.04186 37.69108, 127.04299 ..."
6136,6137.0,6136,1199.542923,103843.895552,6449.155514,5,"MULTIPOLYGON (((127.04866 37.69108, 127.04979 ..."
6137,6138.0,6137,1199.543261,103843.954049,1493.468065,3,"MULTIPOLYGON (((127.04526 37.69264, 127.04639 ..."
6138,6139.0,6138,1199.545028,103844.259974,0.000000,0,"MULTIPOLYGON (((127.02825 37.69421, 127.02939 ..."
6139,6140.0,6139,1199.543499,103843.995140,0.000000,0,"MULTIPOLYGON (((127.04186 37.69420, 127.04299 ..."

In [3]:
import pandas as pd
nobody = 출근시간자전거경로['COUNT']==0
nobody

0        True
1        True
2        True
3        True
4        True
        ...
6135    False
6136    False
6137    False
6138     True
6139     True
Name: COUNT, Length: 6140, dtype: bool

In [4]:
출근시간자전거경로 = 출근시간자전거경로[~nobody]
출근시간자전거경로

,OBJECTID,id,Shape_Leng,Shape_Area,LENGTH,COUNT,geometry
9,10.0,9,1199.568969,103848.405072,27.762222,1,"MULTIPOLYGON (((126.82457 37.51930, 126.82570 ..."
20,21.0,20,1199.530113,103841.677548,60.008702,1,"MULTIPOLYGON (((127.16066 37.57706, 127.16179 ..."
63,64.0,63,1199.541302,103843.614767,80.059095,1,"MULTIPOLYGON (((127.06206 37.44138, 127.06319 ..."
75,76.0,75,1199.544261,103844.127210,254.981844,1,"MULTIPOLYGON (((127.03833 37.44295, 127.03946 ..."
77,78.0,77,1199.553334,103845.698097,3687.049357,8,"MULTIPOLYGON (((126.95689 37.58028, 126.95802 ..."
...,...,...,...,...,...,...,...
6133,6134.0,6133,1199.543395,103843.977230,3128.039877,8,"MULTIPOLYGON (((127.04526 37.68952, 127.04639 ..."
6134,6135.0,6134,1199.542462,103843.815644,2499.978113,7,"MULTIPOLYGON (((127.05206 37.68952, 127.05319 ..."
6135,6136.0,6135,1199.543657,103844.022511,419.969699,5,"MULTIPOLYGON (((127.04186 37.69108, 127.04299 ..."
6136,6137.0,6136,1199.542923,103843.895552,6449.155514,5,"MULTIPOLYGON (((127.04866 37.69108, 127.04979 ..."
6137,6138.0,6137,1199.543261,103843.954049,1493.468065,3,"MULTIPOLYGON (((127.04526 37.69264, 127.04639 ..."

In [ ]:
map = folium.Map(location=[37.5502, 126.982], zoom_start=11)




map.choropleth(geo_data = geo_str,

               data = crime_anal_norm['범죄'],

               columns = [crime_anal_norm.index, crime_anal_norm['범죄']],

               fill_color = 'PuRd', key_on='feature.id')

In [4]:
퇴근시간자전거경로 = gpd.read_file('data/자전거 이용 데이터/퇴근시간대 자전거 이동경로 분포도(2019.10).geojson')
퇴근시간자전거경로

,OBJECTID,id,Shape_Leng,Shape_Area,LENGTH,COUNT,geometry
0,1.0,0,1199.542584,103843.836728,0.000000,0,"MULTIPOLYGON (((127.05188 37.42734, 127.05301 ..."
1,2.0,1,1199.543181,103843.940068,0.000000,0,"MULTIPOLYGON (((127.04849 37.42890, 127.04962 ..."
2,3.0,2,1199.542348,103843.795889,0.000000,0,"MULTIPOLYGON (((127.05527 37.42890, 127.05640 ..."
3,4.0,3,1199.541515,103843.651618,0.000000,0,"MULTIPOLYGON (((127.06205 37.42890, 127.06318 ..."
4,5.0,4,1199.543556,103844.005026,0.000000,0,"MULTIPOLYGON (((127.04510 37.43046, 127.04623 ..."
...,...,...,...,...,...,...,...
6135,6136.0,6135,1199.543657,103844.022511,1201.534057,9,"MULTIPOLYGON (((127.04186 37.69108, 127.04299 ..."
6136,6137.0,6136,1199.542923,103843.895552,28458.465407,22,"MULTIPOLYGON (((127.04866 37.69108, 127.04979 ..."
6137,6138.0,6137,1199.543261,103843.954049,9213.084749,15,"MULTIPOLYGON (((127.04526 37.69264, 127.04639 ..."
6138,6139.0,6138,1199.545028,103844.259974,0.000000,0,"MULTIPOLYGON (((127.02825 37.69421, 127.02939 ..."
6139,6140.0,6139,1199.543499,103843.995140,0.000000,0,"MULTIPOLYGON (((127.04186 37.69420, 127.04299 ..."

In [5]:
nobody = 퇴근시간자전거경로['COUNT']==0
nobody
퇴근시간자전거경로 = 퇴근시간자전거경로[~nobody]
퇴근시간자전거경로

,OBJECTID,id,Shape_Leng,Shape_Area,LENGTH,COUNT,geometry
9,10.0,9,1199.568969,103848.405072,219.933039,1,"MULTIPOLYGON (((126.82457 37.51930, 126.82570 ..."
18,19.0,18,1199.537077,103842.883373,695.643670,1,"MULTIPOLYGON (((127.09953 37.57713, 127.10066 ..."
65,66.0,65,1199.566753,103848.021472,2582.132578,3,"MULTIPOLYGON (((126.84141 37.58018, 126.84254 ..."
74,75.0,74,1199.552891,103845.621409,658.146167,1,"MULTIPOLYGON (((126.96374 37.44295, 126.96487 ..."
77,78.0,77,1199.553334,103845.698097,5388.405776,14,"MULTIPOLYGON (((126.95689 37.58028, 126.95802 ..."
...,...,...,...,...,...,...,...
6133,6134.0,6133,1199.543395,103843.977230,11331.349780,23,"MULTIPOLYGON (((127.04526 37.68952, 127.04639 ..."
6134,6135.0,6134,1199.542462,103843.815644,8476.814996,21,"MULTIPOLYGON (((127.05206 37.68952, 127.05319 ..."
6135,6136.0,6135,1199.543657,103844.022511,1201.534057,9,"MULTIPOLYGON (((127.04186 37.69108, 127.04299 ..."
6136,6137.0,6136,1199.542923,103843.895552,28458.465407,22,"MULTIPOLYGON (((127.04866 37.69108, 127.04979 ..."
6137,6138.0,6137,1199.543261,103843.954049,9213.084749,15,"MULTIPOLYGON (((127.04526 37.69264, 127.04639 ..."